<?php

namespace Framework\Models\Posts;
use Framework\Models\Basic\Model;
use Framework\Modules\ORM;

class GetLikesAmount extends Model
{
    protected function process()
    {
        parent::process(); // TODO: Change the autogenerated stub
    }

}